spring.application.name=Groccy
# server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/groccy
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.error.include-message= always